// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Handlers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheseusControlStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheseusControlStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Handlers.TheseusControlStrings", typeof(TheseusControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Shutdown_Note {
            get {
                return ResourceManager.GetString("Shutdown.Note", resourceCulture);
            }
        }
        
        internal static string Shutdown_Command {
            get {
                return ResourceManager.GetString("Shutdown.Command", resourceCulture);
            }
        }
        
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help.Usage", resourceCulture);
            }
        }
        
        internal static string Help_Note {
            get {
                return ResourceManager.GetString("Help.Note", resourceCulture);
            }
        }
        
        internal static string Help_Command {
            get {
                return ResourceManager.GetString("Help.Command", resourceCulture);
            }
        }
        
        internal static string Help_PrintTitle {
            get {
                return ResourceManager.GetString("Help.PrintTitle", resourceCulture);
            }
        }
        
        internal static string Shutdown_Usage {
            get {
                return ResourceManager.GetString("Shutdown.Usage", resourceCulture);
            }
        }
    }
}
