// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Handlers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MinecraftStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MinecraftStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Handlers.MinecraftStrings", typeof(MinecraftStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Unban_Command {
            get {
                return ResourceManager.GetString("Unban.Command", resourceCulture);
            }
        }
        
        internal static string Ban_Command {
            get {
                return ResourceManager.GetString("Ban.Command", resourceCulture);
            }
        }
        
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        internal static string Players_Note {
            get {
                return ResourceManager.GetString("Players.Note", resourceCulture);
            }
        }
        
        internal static string Unban_Note {
            get {
                return ResourceManager.GetString("Unban.Note", resourceCulture);
            }
        }
        
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        internal static string OptionsParseError {
            get {
                return ResourceManager.GetString("OptionsParseError", resourceCulture);
            }
        }
        
        internal static string Servers_Command {
            get {
                return ResourceManager.GetString("Servers.Command", resourceCulture);
            }
        }
        
        internal static string Ban_Ok {
            get {
                return ResourceManager.GetString("Ban.Ok", resourceCulture);
            }
        }
        
        internal static string Servers_Usage {
            get {
                return ResourceManager.GetString("Servers.Usage", resourceCulture);
            }
        }
        
        internal static string Ban_Usage {
            get {
                return ResourceManager.GetString("Ban.Usage", resourceCulture);
            }
        }
        
        internal static string Unban_Usage {
            get {
                return ResourceManager.GetString("Unban.Usage", resourceCulture);
            }
        }
        
        internal static string Unban_Ok {
            get {
                return ResourceManager.GetString("Unban.Ok", resourceCulture);
            }
        }
        
        internal static string PlayerNameMissing {
            get {
                return ResourceManager.GetString("PlayerNameMissing", resourceCulture);
            }
        }
        
        internal static string Servers_PrintTitle {
            get {
                return ResourceManager.GetString("Servers.PrintTitle", resourceCulture);
            }
        }
        
        internal static string Servers_Note {
            get {
                return ResourceManager.GetString("Servers.Note", resourceCulture);
            }
        }
        
        internal static string Players_PrintTitle {
            get {
                return ResourceManager.GetString("Players.PrintTitle", resourceCulture);
            }
        }
        
        internal static string Players_Usage {
            get {
                return ResourceManager.GetString("Players.Usage", resourceCulture);
            }
        }
        
        internal static string Ban_Note {
            get {
                return ResourceManager.GetString("Ban.Note", resourceCulture);
            }
        }
        
        internal static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        internal static string Players_Command {
            get {
                return ResourceManager.GetString("Players.Command", resourceCulture);
            }
        }
        
        internal static string Time_Forever {
            get {
                return ResourceManager.GetString("Time.Forever", resourceCulture);
            }
        }
    }
}
