// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Handlers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Handlers.AuthStrings", typeof(AuthStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login_Command {
            get {
                return ResourceManager.GetString("Login.Command", resourceCulture);
            }
        }
        
        internal static string Whoami_Command {
            get {
                return ResourceManager.GetString("Whoami.Command", resourceCulture);
            }
        }
        
        internal static string Login_Ok {
            get {
                return ResourceManager.GetString("Login.Ok", resourceCulture);
            }
        }
        
        internal static string Login_Usage {
            get {
                return ResourceManager.GetString("Login.Usage", resourceCulture);
            }
        }
        
        internal static string Login_Note {
            get {
                return ResourceManager.GetString("Login.Note", resourceCulture);
            }
        }
        
        internal static string Whoami_Usage {
            get {
                return ResourceManager.GetString("Whoami.Usage", resourceCulture);
            }
        }
        
        internal static string Login_BetterRoleWarning {
            get {
                return ResourceManager.GetString("Login.BetterRoleWarning", resourceCulture);
            }
        }
        
        internal static string Login_InvalidLoginPass {
            get {
                return ResourceManager.GetString("Login.InvalidLoginPass", resourceCulture);
            }
        }
        
        internal static string Whoami_Note {
            get {
                return ResourceManager.GetString("Whoami.Note", resourceCulture);
            }
        }
        
        internal static string Login_ArgsError {
            get {
                return ResourceManager.GetString("Login.ArgsError", resourceCulture);
            }
        }
    }
}
